"""Packing a dev area into a movable tarball.

The artifact holds only the dev builds -- a few megabytes -- and assumes the target
mounts the same Spack store at the same path. That is what keeps it small: the store
paths baked into the dev libraries' RUNPATHs still resolve on arrival, so nothing but
the dev builds has to travel.

**Relocation is by LD_LIBRARY_PATH, never by rewriting binaries.** That is a
deliberate refusal, not an omission. ``spack.relocate.relocate_elf_binaries`` falls
back to ``patchelf --force-rpath --set-rpath`` (``relocate.py:186``) whenever its
in-place ELF patch will not fit, and ``--force-rpath`` converts DT_RUNPATH into
DT_RPATH -- which would silently destroy the shadowing this whole tool rests on.
Spack has no ``$ORIGIN`` generation and ``make_elf_binaries_relative`` was removed in
0.20. Since dev builds already carry DT_RUNPATH, putting the unpacked location on
LD_LIBRARY_PATH is both sufficient and safe.
"""

import json
import os
import shlex

import spack.error
import spack.util.tty as tty
import spack.store
import spack.util.archive as archive

#: Substituted into the generated scripts so they work wherever they are unpacked.
ROOT_VAR = "SPLICE_ROOT"

#: Variables that name a single directory rather than a search path, and so must not
#: be rewritten to point inside the tarball.
_NOT_PATHS = ("SPACK_SPLICE_DIR",)


class PackError(spack.error.SpackError):
    """Raised when a dev area cannot be packed."""


def _dquote(value: str, dev_area: str) -> str:
    """Double-quote a value, keeping ``${SPLICE_ROOT}`` expandable.

    ``shlex.quote`` would wrap the whole thing in single quotes and stop the
    placeholder from ever expanding, so the escaping is done by hand: everything
    the shell would interpret inside double quotes, and only then the placeholder
    substitution, which deliberately reintroduces an unescaped ``$``.
    """
    out = value
    for char in ("\\", '"', "`", "$"):
        out = out.replace(char, "\\" + char)
    return out.replace(dev_area, "${%s}" % ROOT_VAR)


def _export_lines(resolved, path_vars, dev_area):
    """Shell ``export`` lines for the packed environment.

    Built by hand rather than via ``EnvironmentModifications.shell_modifications``,
    which is wrong here in two separate ways. It defaults to ``env=os.environ`` and
    emits fully *resolved* values, so it bakes the packing machine's own PATH into
    the artifact; and it always emits a flat assignment, which on the target would
    **replace** PATH rather than extend it -- leaving a shell with no ``/usr/bin``
    and no ``head``, as this did before the fix.

    So path-like variables are emitted in prepend form, ``${VAR:+:$VAR}``, keeping
    whatever the target already had.
    """
    lines = []
    for name in sorted(resolved):
        if name in _NOT_PATHS:
            continue
        value = resolved[name]
        if name in path_vars:
            lines.append(f'export {name}="{_dquote(value, dev_area)}${{{name}:+:${name}}}";')
        elif dev_area in value:
            lines.append(f'export {name}="{_dquote(value, dev_area)}";')
        else:
            lines.append(f"export {name}={shlex.quote(value)};")
    return lines


SETUP_HEADER = """\
#!/bin/sh
# Generated by 'spack splice pack'. Source this file:  . ./setup.sh
#
# Only the dev builds are in this tarball. Everything they depend on still comes
# from the Spack store below, so that store has to be present at this exact path.
{root_discovery}
if [ ! -d "{store}" ]; then
    echo "splice: Spack store not found at {store}" >&2
    echo "splice: this tarball only carries the dev builds; the rest of the stack" >&2
    echo "splice: must be reachable at that path." >&2
    return 1 2>/dev/null || exit 1
fi

"""

#: Locating the script from inside itself, portably.
#:
#: ``${BASH_SOURCE}`` without a subscript is deliberate: the ``[0]`` form is a bash
#: array reference and dash rejects it outright with "Bad substitution", killing the
#: script. Bare ``$BASH_SOURCE`` yields element zero under bash and expands to
#: nothing everywhere else, so the ``$0`` fallback takes over.
#:
#: Honouring a pre-set SPLICE_ROOT is what lets ``run.sh`` work under dash, where a
#: sourced script's ``$0`` is the shell rather than the file.
ROOT_DISCOVERY = f"""\
if [ -z "${{{ROOT_VAR}:-}}" ]; then
    _splice_self="${{BASH_SOURCE:-$0}}"
    {ROOT_VAR}="$(cd "$(dirname "$_splice_self")" && pwd)"
fi
export {ROOT_VAR}

if [ ! -d "${{{ROOT_VAR}}}/install" ]; then
    echo "splice: {ROOT_VAR}=${{{ROOT_VAR}}} has no install/ directory." >&2
    echo "splice: source this from bash or zsh, or use ./run.sh <command>." >&2
    return 1 2>/dev/null || exit 1
fi
"""


def setup_script(resolved, path_vars, dev_area, store_root):
    body = "\n".join(_export_lines(resolved, path_vars, dev_area))
    header = SETUP_HEADER.format(root_discovery=ROOT_DISCOVERY, store=store_root)
    return header + body + "\n"


def run_script():
    """A wrapper that works even under dash, where a sourced ``$0`` is the shell.

    It resolves the root from its own ``$0`` -- reliable, because run.sh is
    *executed* rather than sourced -- and exports it so setup.sh skips its own
    discovery.
    """
    return f"""\
#!/bin/sh
# Generated by 'spack splice pack'.  Usage:  ./run.sh <command> [args...]
if [ $# -eq 0 ]; then
    echo "usage: $0 <command> [args...]" >&2
    exit 2
fi
{ROOT_VAR}="$(cd "$(dirname "$0")" && pwd)"
export {ROOT_VAR}
. "${{{ROOT_VAR}}}/setup.sh" || exit 1
exec "$@"
"""


def modulefile(resolved, path_vars, dev_area, store_root):
    """A TCL modulefile applying the same environment.

    Search paths use ``prepend-path`` so the module composes with whatever the user
    already has loaded; only genuinely single-valued variables use ``setenv``.
    Getting that distinction wrong would clobber the caller's PATH, exactly as the
    shell script did before it learned to prepend.

    ``prepend-path`` entries are emitted in reverse so that, after each is pushed to
    the front, the final order matches ``resolved``.
    """
    lines = [
        "#%Module1.0",
        "# Generated by 'spack splice pack'.",
        "set root [file dirname [file normalize $ModulesCurrentModulefile]]",
        f'if {{![file isdirectory "{store_root}"]}} {{',
        f'    puts stderr "splice: Spack store not found at {store_root}"',
        "}",
    ]
    for name in sorted(resolved):
        if name in _NOT_PATHS:
            continue
        value = resolved[name]
        if name not in path_vars:
            lines.append(f"setenv {name} {{{value}}}")
            continue
        for entry in reversed([e for e in value.split(os.pathsep) if e]):
            if entry.startswith(dev_area):
                rel = entry[len(dev_area) :].lstrip("/")
                lines.append(f'prepend-path {name} [file join $root "{rel}"]')
            else:
                lines.append(f"prepend-path {name} {{{entry}}}")
    return "\n".join(lines) + "\n"


def provenance(cfg, root, prefixes, spliced=None):
    """What this artifact is and what it needs, as JSON.

    Self-describing on purpose: an unpacked tarball on another machine is otherwise
    an anonymous pile of prefixes. ``cfg`` is the dev area's ``splice.yaml`` body.
    """
    packages = cfg.get("packages") or {}
    return {
        "splice": {
            "base": {
                "spec": cfg.get("spec"),
                "hash": cfg.get("hash"),
                "environment": cfg.get("environment"),
            },
            "arch": str(root.architecture),
            "store_root": str(spack.store.STORE.layout.root),
            "dev_packages": {
                name: {
                    "prefix_basename": os.path.basename(prefix),
                    "source": packages.get(name, {}).get("path"),
                }
                for name, prefix in sorted(prefixes.items())
            },
            "spliced_spec": json.loads(spliced.to_json()) if spliced is not None else None,
        }
    }


def create(area, cfg, prefixes, resolved, path_vars, root, output, spliced=None):
    """Write ``output`` (a .tar.gz) containing the dev builds and the scripts.

    Uses ``spack.util.archive`` rather than ``tarfile`` directly: it already zeroes
    mtimes, normalizes ownership to root and permissions git-style, sorts entries and
    dedups hardlinks, so the artifact is reproducible.

    Deliberately *not* ``binary_distribution.create_tarball`` -- that injects a
    ``.spack/binary_distribution`` member and is tied to the store layout through
    ``get_buildinfo_dict``. This is not a buildcache entry.
    """
    present = {n: p for n, p in prefixes.items() if os.path.isdir(p)}
    if not present:
        raise PackError(
            "nothing to pack: no dev package has been built",
            "Run 'spack splice build' first.",
        )

    name = os.path.basename(output)
    for suffix in (".tar.gz", ".tgz"):
        if name.endswith(suffix):
            name = name[: -len(suffix)]
            break

    store_root = str(spack.store.STORE.layout.root)
    files = {
        f"{name}/setup.sh": (
            setup_script(resolved, path_vars, area, store_root),
            0o755,
        ),
        f"{name}/run.sh": (run_script(), 0o755),
        f"{name}/modulefile": (
            modulefile(resolved, path_vars, area, store_root),
            0o644,
        ),
        f"{name}/splice.json": (
            json.dumps(provenance(cfg, root, present, spliced), indent=2, sort_keys=True)
            + "\n",
            0o644,
        ),
    }

    os.makedirs(os.path.dirname(os.path.abspath(output)) or ".", exist_ok=True)
    with archive.gzip_compressed_tarfile(output) as (tar, gz_checksum, _):
        for pkg, prefix in sorted(present.items()):
            base = os.path.basename(prefix)
            archive.reproducible_tarfile_from_prefix(
                tar,
                prefix,
                path_to_name=lambda p, _pfx=prefix, _b=base: (
                    f"{name}/install/{_b}" + p[len(_pfx) :].replace(os.sep, "/")
                ),
            )
        for entry, (text, mode) in files.items():
            _add_text(tar, entry, text, mode)

    return output, gz_checksum.hexdigest(), sorted(present)


def _add_text(tar, entry_name: str, text: str, mode: int) -> None:
    """Add a generated file with the same zeroed metadata archive.py uses."""
    import io
    import tarfile

    data = text.encode("utf-8")
    info = tarfile.TarInfo(entry_name)
    info.size = len(data)
    info.mode = mode
    # mtime/uid/gid default to 0 and "" -- matching reproducible_tarfile_from_prefix.
    tar.addfile(info, io.BytesIO(data))
